dependencies:
- name: cargotracker-handling
  version: 0.0.10
  repository: https://artifactory-tools.workshop-ocp43-on-740499-7ec5d722a0ab3f463fdc90eeb94dbc70-0000.us-east.containers.appdomain.cloud/artifactory/generic-local/workshop-team-one/
