global:
  ingressSubdomain: workshop-ocp43-on-740499-7ec5d722a0ab3f463fdc90eeb94dbc70-0000.us-east.containers.appdomain.cloud
  tlsSecretName: workshop-ocp43-on-740499-7ec5d722a0ab3f463fdc90eeb94dbc70-0000

cargotracker-handling:
  replicaCount: 1
  logLevel: "fatal"

  credentials:
    dbusername: "aGFuZGxpbmdtc2Ri"
    dbpassword: "aGFuZGxpbmdtc2Ri"
    mqusername: "YXBwdXNlcg=="
    mqpassword: "cGFzc3cwcmQ="
  datasources:
    dburl: "jdbc:mysql://mysql-prod:3306/handlingmsdb?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=EST"
    mqhost: "rabbitmq-prod-headless"
    mqport: "5672" 

  partOf: "cargotracker-backend-prod"
  connectsTo: "mysql-prod, rabbitmq-prod"      
  
  ingress:
    enabled: true
    tlsSecretName: workshop-ocp43-on-740499-7ec5d722a0ab3f463fdc90eeb94dbc70-0000

