global:
  ingressSubdomain: sandbox-ocp43-one-462537-b2e73aa4eddf9dc566faa4f42ccdd306-0000.eu-gb.containers.appdomain.cloud
  tlsSecretName: sandbox-ocp43-one-462537-b2e73aa4eddf9dc566faa4f42ccdd306-0000

cargotracker-handling:
  replicaCount: 1
  logLevel: "fatal"

  credentials:
    dbusername: "aGFuZGxpbmdtc2Ri"
    dbpassword: "aGFuZGxpbmdtc2Ri"
    mqusername: "YXBwdXNlcg=="
    mqpassword: "cGFzc3cwcmQ="
  datasources:
    dburl: "jdbc:mysql://mysql-test:3306/handlingmsdb?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=EST"
    mqhost: "rabbitmq-test-headless"
    mqport: "5672"

  partOf: "cargotracker-backend-test"
  connectsTo: "mysql-test, rabbitmq-test"   
  
  ingress:
    enabled: true
    tlsSecretName: sandbox-ocp43-one-462537-b2e73aa4eddf9dc566faa4f42ccdd306-0000

