global:
  ingressSubdomain: workshop-ocp43-on-740499-7ec5d722a0ab3f463fdc90eeb94dbc70-0000.us-east.containers.appdomain.cloud
  tlsSecretName: workshop-ocp43-on-740499-7ec5d722a0ab3f463fdc90eeb94dbc70-0000

cargotracker-routing:
  replicaCount: 1
  logLevel: "fatal"

  credentials:
    dbusername: "cm91dGluZ21zZGI="
    dbpassword: "cm91dGluZ21zZGI="
    mqusername: "YXBwdXNlcg=="
    mqpassword: "cGFzc3cwcmQ="
  datasources:
    dburl: "jdbc:mysql://mysql-prod:3306/routingmsdb?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=EST"
    mqhost: "rabbitmq-prod-headless"
    mqport: "5672"   
  
  ingress:
    enabled: true
    tlsSecretName: workshop-ocp43-on-740499-7ec5d722a0ab3f463fdc90eeb94dbc70-0000

