global:
  ingressSubdomain: sandbox-ocp43-one-462537-b2e73aa4eddf9dc566faa4f42ccdd306-0000.eu-gb.containers.appdomain.cloud
  tlsSecretName: sandbox-ocp43-one-462537-b2e73aa4eddf9dc566faa4f42ccdd306-0000

cargotracker-bff:
  replicaCount: 1
  logLevel: "fatal"
  
  serviceUrl: "cargotracker-booking.cargotracker-backend-test:80"

  partOf: "cargotracker-frontend-test"
  connectsTo: ""
  
  ingress:
    enabled: true
    tlsSecretName: sandbox-ocp43-one-462537-b2e73aa4eddf9dc566faa4f42ccdd306-0000

