global:
  ingressSubdomain: sandbox-ocp43-one-462537-b2e73aa4eddf9dc566faa4f42ccdd306-0000.eu-gb.containers.appdomain.cloud
  tlsSecretName: sandbox-ocp43-one-462537-b2e73aa4eddf9dc566faa4f42ccdd306-0000

cargotracker-ui:
  replicaCount: 1
  logLevel: "fatal"
  
  partOf: "cargotracker-frontend-test"
  connectsTo: "cargotracker-frontend-bff-svc"
  
  ingress:
    enabled: true
    tlsSecretName: sandbox-ocp43-one-462537-b2e73aa4eddf9dc566faa4f42ccdd306-0000

